apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "torchserve-grpc-v2"
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      protocolVersion: v2
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v2
      ports:
        - containerPort: 8081
          name: h2c
          protocol: TCP
