apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-migration-svcaccount
  namespace: kserve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-migration-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.kubeflow.org
  resources:
  - inferenceservices
  - inferenceservices/finalizers
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  - inferenceservices/finalizers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-migration-rolebinding
subjects:
- kind: ServiceAccount
  name: cluster-migration-svcaccount
  apiGroup: ""
  namespace: kserve
roleRef:
  kind: ClusterRole
  name: cluster-migration-role
  apiGroup: ""
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kserve-migration
  namespace: kserve
spec:
  template:
    metadata:
      name: kserve-migration
    spec:
      serviceAccountName: cluster-migration-svcaccount
      containers:
      - name: kserve-migration
        image: kserve/kserve-migration:latest
      restartPolicy: Never