apiVersion: "serving.kserve.io/v1alpha3"
kind: "Service"
metadata:
  name: "tensorflow-gpu"
spec:
  predictor:
    tensorflow:
      storageUri: "gs://kfserving-examples/models/tensorflow/flowers"
      resources:
        limits:
          nvidia.com/gpu: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: nvidia-tesla-k80
