import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  GettingStartedSidebar: [

    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'Getting_Started/README',
        'Getting_Started/first_isvc',
        'Getting_Started/swagger_ui',
      ],
    },
    
  ],
  adminSidebar: [
    {
      type: 'category',
      label: 'Administration Guide',
      items: [
        {
          type: 'category',
          label: 'Serverless',
          items: [
            'admin/serverless/serverlesss',
            'admin/serverless/servicemesh/README',
            'admin/serverless/kourier_networking/README',
          ],
        },
        'admin/modelmesh',
        'admin/kubernetes_deployment',
        'admin/migration',
      ],
    },
  ],
};
export default sidebars;
